# Generated by Django 4.2.26 on 2025-11-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myRestaurant.usuario'),
        ),
    ]
