# Generated by Django 4.2 on 2025-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRestaurant', '0002_reservacion_email_cliente_reservacion_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, help_text='Ej: Chef, Mesero', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.CharField(blank=True, help_text='Ej: Matutino, Vespertino', max_length=50, null=True),
        ),
    ]
